### ISSUE TITLE
Add dark theme.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [browserpass/browserpass#243]
Could you add dark theme please.

**Comment by maximbaz** [comment]
I would gladly accept a PR for the dark theme 🙂

I suggest looking into creating small stylesheet file that can work on top of existing styles to only override some colors, so that we decrease the maintenance for the two themes.

Then create a new option on the options page with the dropdown selector for the theme. When "dark" is selected, inject the additional override styles where applicable.

**Comment by maximbaz** [comment]
The next version of browserpass will have dark theme:

![image](https://user-images.githubusercontent.com/1177900/46921623-ea564d00-cffd-11e8-8280-65cfbd34a9d3.png)

**Comment by c-e-p-x-u-o** [comment]
Thank you! (:
