### ISSUE TITLE
Support submit buttons with "form" attribute located anywhere on a page

### ISSUE THREAD

**Issue by mcnesium** [browserpass/browserpass#261]
Since recently I see the auto login fail on Discourse forums [like this one](https://meta.discourse.org). No idea whether this is due to a Discourse update or browserpass changes.

**Comment by mcnesium** [comment]
[I reported the issue](https://meta.discourse.org/t/login-form-is-invalid-html/87735). Lets see what happens…

**Comment by mcnesium** [comment]
[the answer](https://meta.discourse.org/t/login-form-is-invalid-html/87735/2):
> Submit buttons does not have to be a child of the HTML `<form>` element.
> I recently added the form attribute to the Login button to help password managers.

While I personally disagree with the habit, I must admit that technically he is right: [`<button>` specs at MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button). 

Looks like [his commit](https://github.com/discourse/discourse/commit/8c91d418ddc240cf6f1faf3561c140b1bdbce130) will only land in Discourse v2.0, but you could be prepared for that, if browserpass can not handle the `form` attribute yet.

**Comment by maximbaz** [comment]
Great finding, I didn't know it's a thing - definitely will implement.

**Comment by mcnesium** [comment]
[bug report](https://meta.discourse.org/t/login-button-form-attribute/109828) :tada:

**Comment by maximbaz** [comment]
I've looked into this, the fact that they fixed "form" attribute is great, but the reason why Browserpass is still unable to detect the login button is because there are no "markers" on the button that would confirm that it is indeed a login button. I don't want Browserpass to click random buttons, so I posted an explanation on their Github asking to add any identifying label, in `id`, `name` or `class` attribute.

See https://github.com/discourse/discourse/pull/7056#issuecomment-478290102

I tested that when I edit HTML in Chromium Devtools and add for example `class="login"` to the Login button, Browserpass correctly detects it.

So at the moment there's nothing else to do on our side, but Discourse team needs to identify their login button better.
