### ISSUE TITLE
Open URL meta-field is being ignored

### ISSUE THREAD

**Issue by uri** [browserpass/browserpass#262]
### General information

* Operating system + version: macOS 10.13.4

* Browser + version: Chrome  66.0.3359.181
* Information about the host app:
  * How did you install it?
    * Downloaded a pre-built binary
  * If installed an official release, put a version: 2.0.21
* Information about the browser extension:
  * How did you install it?
    * Installed via webstore
  * Browserpass extension version as reported by your browser: 2.0.21

---

### Exact steps to reproduce the problem
1. Create a multiline entry in pass with a [*Open Url* meta field](https://github.com/browserpass/browserpass#open-url).

```
# example.com.gpg
password1
username: my-name
url: https://example.com/login
```

2. Invoke extension via keyboard shortcut (cmd+l in my case)
3. Find this entry
4. <kbd>Tab</kbd>, <kbd>g</kbd>

### What should happen?

Browser should navigate to *https://example.com/login*

### What happened instead?

Browser navigates to *https://example.com*

**Comment by maximbaz** [comment]
I cannot reproduce, my best guess is that an old binary is still alive somewhere on your system at takes over the new binary.

Check the manifest file in either `/Library/Google/Chrome/NativeMessagingHosts` or `$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts`, look to which browserpass binary it points. Then try to run that binary with `-v` and check the version.

Another test to do is to rename your file from `example.com.gpg` to `example.gpg`, my guess is that extension will complain on the absence of the `url` property in the file, possibly because of the old host app.

**Comment by uri** [comment]
I found a file in `$HOME/Library/Application Support/Google/Chrome/NativeMessagingHost`

1. `com.dannyvankooten.browserpass.json` points to a binary that has the version: `Browserpass host app version: 2.0.21`

**Comment by uri** [comment]
I see what's happening. The login URL I was using was actually redirecting me without me noticing! My bad.
