### ISSUE TITLE
Problem with submitting AWS login page

### ISSUE THREAD

**Issue by edwlarkey** [browserpass/browserpass#268]
### General information

* Operating system + version: MacOS 10.13.5
* Browser + version: Firefox 60.0.2
* Information about the host app:
  * How did you install it?
    * Downloaded a pre-built binary from the releases page
  * If installed an official release, put a version: 
    * v2.0.21
* Information about the browser extension:
  * How did you install it?
    * Firefox webstore
  * Browserpass extension version as reported by your browser:
    * 2.0.21

---

### Exact steps to reproduce the problem
1. On AWS login page (for IAM user, not root)
2. Fill and submit with browserpass

### What should happen?

I should be logged into AWS or taken to a 2 factor auth page

### What happened instead?

I get a page with a json error 

```{"state":"FAIL","properties":{"Message":"Invalid request","Title":"Bad Request","header":"Bad Request","text":"Invalid request"}}```

If I copy the password with browserpass paste it in manually, submit works fine. If I set `autoSubmit: false`, and just use browserpass to fill the form, submit also works fine.

**Comment by maximbaz** [comment]
I have a strong suspicion that this will be solved by #261, when browserpass learns how to submit those special forms. Let's keep this open and verify once that ticket is solved.

**Comment by maximbaz** [comment]
The page with json error has been solved in https://github.com/browserpass/browserpass-extension/pull/52

Because AWS uses non-standard HTML markup, Browserpass is unable to detect the login button. In v3 (#331) I implemented a way to make Browserpass fake Enter keypress for you (https://github.com/browserpass/browserpass-extension/pull/55), but sadly this only works in Chromium(-based?) browser, not in Firefox.
