### ISSUE TITLE
Extension Windows path support

### ISSUE THREAD

**Issue by braderhart** [browserpass/browserpass#278]
### General information

* Operating system + version: Windows 10
* Browser + version: Chromium 67.0.3396.99 (64-bit)
* Information about the host app:
  * How did you install it?
    * Pre-built binary
  * If installed an official release, put a version: 2.0.21
* Information about the browser extension:
    * Installed via webstore
  * Browserpass extension version as reported by your browser: 2.0.21

---

### Exact steps to reproduce the problem
1. Create new Password Store location in Extension options
2. Enter Windows path to location

### What should happen?
Passwords should show up and work

### What happened instead?
Passwords show up prefixed with path and do not work

**Comment by erayd** [comment]
Hi @braderhart - could you please provide a screenshot? Files are supposed to be listed with a path prefix relative to the store root.

When you say they "do not work", what exactly happens, and what were you expecting?

**Comment by braderhart** [comment]
![Options](https://i.imgur.com/MqKj54v.png)
My options.

![Links](https://i.imgur.com/5OGlTL9.png)
Default .password-store users disappear

![Error](https://i.imgur.com/pwZrFBy.png)
Error on selecting password option.

What I would like to happen if possible, is an option to merge the passwords display so they work without the prefix and no error too if possible.

**Comment by erayd** [comment]
@braderhart What you're asking for already exists, if I understand you correctly :-).

When you set up custom store locations, this overrides the default. What your screenshot shows is that you have only one store configured - `C:\Users\berhart\.password-store-brad`.

In order to display merged results, you need to configure more than one store:

| name | path |
| --- | --- |
| Default | C:\Users\berhart\.password-store |
| Brad | C:\Users\berhart\.password-store-brad |

Removing the prefix is also a thing - you simply need to provide a name for your configured stores. If a name is available, then the prefix is removed and the store name is displayed instead.

**Comment by erayd** [comment]
@maximbaz I think there's a bug in here also - based on @braderhart's screenshot, it looks like when a custom store is configured with no name, then something strange is happening with the prefix when fetching the file. I will look into this...

**Comment by braderhart** [comment]
@erayd This works perfectly now. Thanks!

**Comment by maximbaz** [comment]
I believe this has been fixed in v3, if you can test now, please share your feedback in https://github.com/browserpass/browserpass/issues/331
