### ISSUE TITLE
Settings are sometimes reset in Firefox Nightly

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass#285]
### General information

* Operating system + version: Fedora 28
* Browser + version: Firefox Nightly 64.0
* Information about the host app:
  * How did you install it? I got the release from github and used `install.sh`
  * If installed an official release, put a version: 2.0.22
* Information about the browser extension:
  * How did you install it? Firefox add-ons
  * Browserpass extension version as reported by your browser: browserpass-ce 2.0.22

---

### Exact steps to reproduce the problem

This bug is *not* constantly reproducible.

1. Start Firefox Nightly
2. Right-click on the browserpass-ce icon and `Manage extension`
3. Enable the `Automatically submit forms after filling` setting
4. Restart Firefox

### What should happen?

The setting is enabled

### What happened instead?

Sometimes, the setting becomes disabled again.

**Comment by erayd** [comment]
Does this also occur in other versions of Firefox, or only in Nightly?

**Comment by DamienCassou** [comment]
Erayd <notifications@github.com> writes:
> Does this also occur in other versions of Firefox, or only in Nightly?

I don't know. I have used Nightly only for over a year now. And because
it doesn't happen all the times, it's hard for me to test.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by maximbaz** [comment]
We store settings in localStorage, sounds like local storage is not stable in Firefox Nightly and sometimes gets cleared? I don't think it is an issue in stable Firefox, or we would have heard about this sooner.

I'll close because I'm not sure what we can do about stability of localStorage in Firefox Nightly, Nightly is unstable by definition 😄 

By the way, in v3 you will be able to configure browserpass via a config file stored in your password store directory, that way you won't need to rely on browser to remember your settings. This part is already implemented, but feature parity with v2 is not achieved yet, so I wouldn't recommend using v3 just yet.

**Comment by DamienCassou** [comment]
FYI: I still have the problem.
