### ISSUE TITLE
Allow ignoring results based on regex

### ISSUE THREAD

**Issue by adtac** [browserpass/browserpass#291]
### General information

* Operating system + version: Archlinux
* Browser + version: Firefox Nightly (64.0a1)
* Information about the host app:
  * How did you install it? AUR `browserpass`
  * If installed an official release, put a version: 2.0.21
* Information about the browser extension:
  * How did you install it? https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/
  * Browserpass extension version as reported by your browser: 2.0.22

---

### What should happen?

I store my passwords in the following directory structure:
```
Password Store
|
+-- 2fa-recovery-codes
|   |
|   +-- github.com
|
+-- github.com
    |
    +-- adtac
```

`github.com/adtac` contains the password and `2fa-recovery-codes/github.com` stores my recovery codes.

When I open browserpass on the Github login page, I'm presented with both fields. Obviously, on the browser, I only want to see `github.com/adtac`.

So I want to add a regex filter to ignore certain paths irrespective of what page I'm in (I'll be adding `.*2fa-recovery-codes.*`) so that I only see one result.

**Comment by maximbaz** [comment]
Hi, your scenario is supported by grouping all entries that you want for browserpass to see in a common folder, i.e. make this structure:

.password-store
-- 2fa-recovery-codes
---- github.com
-- passwords
---- github.com

Then in browserpass options add the folder .password-store/passwords as the source of credentials.

**Comment by adtac** [comment]
Thanks, that solved the issue for me, but I think this issue is still a valid one for other people.

**Comment by erayd** [comment]
@maximbaz This would be fairly simple to add in the v3 options. I have no use for it, but I also have no objection to adding it. Thoughts?

**Comment by maximbaz** [comment]
I agree that it is simple to implement, but I simply don't feel this is right approach. The whole concept is that you manage your password store by organizing files on your file system, separation between what should and should not appear in browserpass really better be done by grouping files in subfolders — that's why we implemented `Custom store locations` setting in the first place 🙂. 

Keeping both work and personal passwords, or both your and your partner's passwords in the single `.password-store` fall into the same category as this ticket.

My other issue is that by allowing to create filters like `.*2fa-recovery-codes.*` browserpass will mistakenly exclude legitimate websites like `https://my2fa-recover-codes.com`.

Because of the above, and because none of us now really have any use for regex filtering, I don't think we should do it.
