### ISSUE TITLE
Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by simendsjo** [browserpass/browserpass#299]
### General information

* Operating system + version: NixOS 18.09.1228.a4c4cbb613c (Jellyfish)
* Browser + version: Chromium 70.0.3538.67 / Chrome 70.0.3538.67
* Information about the host app: Installed through NixOs. Version 2.0.18
* Information about the browser extension: Installed through regular store. Version 2.0.22

---

### Exact steps to reproduce the problem
1. Press the `browserpass` symbol
2. The error shows below the search field

**Comment by maximbaz** [comment]
Hi there, it sounds like NixOS package is broken and the browser extension cannot discover browserpass. It's a pity, I would prefer users to install the app via package managers, not manually 🙁 

NixOS package is managed by community, I highly encourage you to investigate and fix the NixOS package (and update it to the latest version). Let me know if you will be looking into it — if not, I think I should remove it from README 🤔 

I'm closing because I won't be investigating this myself.

**Comment by simendsjo** [comment]
Not sure how to debug this as I get no indication on what's wrong. I'll add the issue to nixpkgs and see if I can get in touch with anyone.

**Comment by aij** [comment]
Did you try 

    programs.browserpass.enable = true`

?

**Comment by simendsjo** [comment]
> Did you try
> 
> ```
> programs.browserpass.enable = true;
> ```
> ?

Ah! There's my bug! I only installed the package using nix-env, not enabling it.

**Comment by maximbaz** [comment]
Happy to hear you solved it!

**Comment by simendsjo** [comment]
> Happy to hear you solved it!

.. Yes.. That's what happened.. "I" solved it! :)
