### ISSUE TITLE
Please add suport for HTTP basic auth filling in.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [browserpass/browserpass#306]
As I understand Firefox has support now:
https://bugzilla.mozilla.org/show_bug.cgi?id=1334609
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired

**Comment by erayd** [comment]
@c-e-p-x-u-o This is already supported.

Note that in order to use basic auth, you need to open the target site directly from browserpass. This is because, while it's possible to intercept the sith request, there is no API capable of filling the auth modal popup, so we need to fill it before the popup would normally be triggered.

**Comment by c-e-p-x-u-o** [comment]
ok, sorry
