### ISSUE TITLE
When browserpass icon is moved to overflow menu, passwords keyboard scrolling does not work

### ISSUE THREAD

**Issue by apiraino** [browserpass/browserpass#317]
### General information
Sorry for the long title :-)

On Firefox 66.0b5, if I move the icon on the overfloe menu (see picture), I cannot scroll anymore the list of password, after having invoked the popup menu with `CTRL+L`.

On Chromium, everything's fine.

![screenshot from 2019-02-07 14-20-49](https://user-images.githubusercontent.com/6098822/52414515-da9ad100-2ae4-11e9-8887-216b52a4e26f.png)

* Operating system + version: Ubuntu
* Browser + version: Firefox 66.0b5
* Information about the host app:
  * Browserpass extension version as reported by your browser: 2.0.22

---

### Exact steps to reproduce the problem
1. Move browserpass icon to overflow menu
2. go to any website and type CTRL+L 
3.  the menu appears but I cannot insert text to search for a password
4. Need to use the mouse to focus on the popup, then I can search text

### What should happen?
the popup should have keyboard focus

### What happened instead?
the popup does not have keyboard focus

**Comment by maximbaz** [comment]
Unfortunately I don't think there's anything we can do on the extension side, it's not the first time I hear that Firefox likes to steal focus and users need to use mouse to bring the focus back 😞 For example, there's another very annoying issue https://github.com/browserpass/browserpass/issues/200

I'll close because it's not actionable, but if you or anyone else find a solution that we can implement in this project, I would be very happy to reopen the issue (or better yet, merge a PR 😜)

**Comment by apiraino** [comment]
hey @maximbaz thank you so much for the insight; interesting how sometimes Firefox gets in the way when you least expect.

No worries about closing it, good we now have a trace of this behaviour for the next user that might notice this behaviour! :+1:
