### ISSUE TITLE
OTP button must be disabled for records without OTP

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass#321]
The "Copy OTP code" button must not be shown at all or be disabled for records that has no otpauth record.
"Error: Unable to determine the OTP code for this entry." is the worst behavior.

**Comment by maximbaz** [comment]
yeah unfortunately it's not possible, because you need to decrypt the entry before you can know if it has OTP or not, and I shared elsewhere that it's very costly operation and definitely not going to happen. 

We are considering though to remove the OTP button and add "Copy OTP" in right click menu, and lately I've been thinking about removing OTP functionality altogether (#322).

**Comment by 532910** [comment]
Oh, sorry, I realized that it's impossible. Can I close it?
